<?
	function getMime($ext) { # returns Mime Type (string), check the getMimeMode() for download options
		$knownExts = array(
		'gif' => 'image/gif',
		'jpg' => 'image/jpeg',
		'jpeg' => 'image/jpeg',
		'png' => 'image/png',
		'psd' => 'image/psd',
		'zip' => 'application/x-zip-compressed',
		'rar' => 'application/x-rar-compressed',
		'7z' => 'application/x-7z-compressed',
		'doc' => 'application/msword',
		'docx' => 'application/msword',
		'odt' => 'application/vnd.oasis.opendocument.text',
		'rtf' => 'text/richtext',
		'swf' => 'application/x-shockwave-flash',
		'tif' => 'image/tiff',
		'au' => 'audio/basic',
		'pdf' => 'application/pdf',
		'mp3' => 'audio/mpeg',
		'ogg' => 'audio/ogg',
		'ico' => 'image/x-icon',
		'mpg' => 'application/mpeg',
		'mpeg' => 'application/mpeg',
		'qt' => 'video/quicktime',
		'mov' => 'video/quicktime',
		'mp4' => 'video/mpeg',
		'avi' => 'video/avi',
		'mkv' => 'video/x-matroska',
		'txt' => 'text/plain',
		'bat' => 'text/plain',
		'html' => 'text/html',
		'htm' => 'text/html',
		'xml' => 'application/xml',
		'xls' => 'application/vnd.ms-excel',
		'wmv' => 'video/x-ms-wmv',
		'pps' => 'application/vnd.ms-powerpoint',
		'ppt' => 'application/vnd.ms-powerpoint',
		'exe' => 'application/octet-stream',
		'msi' => 'application/x-ole-storage',
		'ps' => 'application/postscript',
		'qif' => 'image/x-quicktime',
		'ai' => 'application/postscript',
		'wma' => 'audio/x-ms-wma',
		'css' => 'text/css',
		'js' => 'text/javascript',
		'rss' => 'application/rss+xml',
		'json' => 'text/javascript'
		);
		return isset($knownExts[$ext])?$knownExts[$ext]:"";
	}

	function getMimeMode($ext,$viewMode=false) { // returns TRUE if should download as ATTACHMENT, false if INLINE
		// if viewMode, will use inline for formats that most browsers can handle
		$knownExts = array(
		'gif' => false,
		'jpg' => false,
		'jpeg' => false,
		'png' => false,
		'psd' => true,
		'zip' => true,
		'rar' => true,
		'7z' => true,
		'doc' => true,
		'docx' => true,
		'odt' => true,
		'rtf' => true,
		'swf' => false,
		'tif' => !$viewMode,
		'au' => !$viewMode,
		'pdf' => !$viewMode,
		'mp3' => !$viewMode,
		'ogg' => !$viewMode,
		'ico' => false,
		'mpg' => !$viewMode,
		'mpeg' => !$viewMode,
		'qt' => !$viewMode,
		'mov' => !$viewMode,
		'mp4' => !$viewMode,
		'avi' => !$viewMode,
		'mkv' => !$viewMode, // do browsers really support this?
		'txt' => false,
		'html' => false,
		'htm' => false,
		'xml' => true,
		'xls' => true,
		'wmv' => !$viewMode,
		'pps' => true,
		'ppt' => true,
		'exe' => true,
		'msi' => true,
		'bat' => true,
		'ps' => true,
		'qif' => !$viewMode,
		'ai' => true,
		'wma' => !$viewMode,
		'css' => false,
		'js' => false,
		'rss' => false,
		'json' => false
		);
		return isset($knownExts[$ext])?$knownExts[$ext]:true;
	}
